 # <font size =10 >What is Python Module?
<font size=4> A Module is a simple python file that contains collections of functions,classes and variable and has a.py extesion file.
    Eg - math, os, datetime
    
- You use module in your program by importing them  
    

In [1]:
import math # importing a module

In [2]:
dir(math) # checking all the variable,funcation,classes etc in the module

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'lcm',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'nextafter',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc',
 'ulp']

In [3]:
math.sqrt(25)

5.0

In [4]:
math.sqrt(9)

3.0

In [5]:
math.pi

3.141592653589793

In [8]:
from math import sqrt , pi
print(sqrt(35))
print(pi)

5.916079783099616
3.141592653589793


In [1]:
import custom_module

In [2]:
emp = custom_module.Employee("rohan",19)
emp.show()

rohan 19


In [3]:
dir(custom_module)

['Employee',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'display',
 'x']

In [5]:
custom_module.x



[1, 2, 3]

# <font size =12> What is Python Library?
- A python library is a group of interconneted modules. It contains code bundles that can be reused in different programs

# <font size =5> Python Libraries 
Various Python libraries make programming easier.
- Numpy
- Pandas
- Scipy
- Matplotlib
- Scikit-learn
<br> Some commonly used libraries are:

In [1]:
import numpy

In [2]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__packag

In [4]:
import pandas

In [5]:
dir(pandas)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__deprecated_num_index_names',
 '__dir__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_testing',
 '

In [6]:
import scipy

In [7]:
dir(scipy)

['LowLevelCallable',
 '__numpy_version__',
 '__version__',
 'cluster',
 'datasets',
 'fft',
 'fftpack',
 'integrate',
 'interpolate',
 'io',
 'linalg',
 'misc',
 'ndimage',
 'odr',
 'optimize',
 'show_config',
 'signal',
 'sparse',
 'spatial',
 'special',
 'stats',
 'test']

In [8]:
import matplotlib

In [9]:
dir(matplotlib)

['ExecutableNotFoundError',
 'MatplotlibDeprecationWarning',
 'MutableMapping',
 'Parameter',
 'Path',
 'RcParams',
 '_ExecInfo',
 '_VersionInfo',
 '__bibtex__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_add_data_doc',
 '_api',
 '_c_internal_utils',
 '_check_versions',
 '_cm',
 '_cm_listed',
 '_color_data',
 '_deprecated_ignore_map',
 '_deprecated_map',
 '_deprecated_remain_as_none',
 '_docstring',
 '_ensure_handler',
 '_enums',
 '_fontconfig_pattern',
 '_get_config_or_cache_dir',
 '_get_executable_info',
 '_get_ssl_context',
 '_get_version',
 '_get_xdg_cache_dir',
 '_get_xdg_config_dir',
 '_init_tests',
 '_label_from_arg',
 '_log',
 '_logged_cached',
 '_open_file_or_url',
 '_parse_to_version_info',
 '_path',
 '_preprocess_data',
 '_rc_params_in_file',
 '_replacer',
 '_version',
 'atexit',
 'bezier',
 'cbook',
 'checkdep_usetex',
 'cm',
 'color_sequences',
 'colormaps',
 'colors',
 '

# <font size =6> Benefits of Python Libraries

- Easy to learn
- Open source 
- Efficient and multi-platform support
- Huge collection of function and modules
- Big open-source community
- Integrates well with enterprise apps and systems


# <font size = 6> Python Libraries

# Numpy 
- Numpy is a library used for mathematical computations with multi-dimensional numerical data


# Pandas 
- Pandas consist of a variety of analysis tools and configurable high-level data structures.


# Scipy 
- Scientific Pyhton is an open-source high-level scientific computation package. This library is based on a Numpy extension.

# Matplotlib
- It is also an open-soucre library that plots high-definition figures such as pie charts, histograms etc.

# Scikit- learn
- The library contains a lot of efficient tools for machine learning and statistical modeling including classification,regression,clustering and dimensinality reduction.

# <font size = 6>What is an array?
- An array is a central data structure of the Numpy library.
- It is a grid of homegeneous values (same data type).
- The **rank** of the array is the number of dimensions
- The array object in NumPy is called **ndarray**(n dimensional array).

# <font size =6> Introduction to Numpy
- It is a python library used for working with arrays 
- It consists of multidimensional array of objects and a collection them.
- It conduts mathematical and logical operations on arrays.

# <font size = 6> Advantage of Numpy
- It provides an array object that is faster than tranditional Python lists.
- It provides supporting functions.
- Arrays are frequently used in data science.

In [1]:
# Importing numpy
import numpy as np
arr = np.array({1,2,3,5,6})
arr

array({1, 2, 3, 5, 6}, dtype=object)

In [2]:
arr = np.array([1,4,6,4])
arr

array([1, 4, 6, 4])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr = np.array({"3":45,"5":56})
arr


array({'3': 45, '5': 56}, dtype=object)

In [6]:
arr = np.array([1,"string",78,"gaurav",None])
arrṇ 

array([1, 'string', 78, 'gaurav', None], dtype=object)

In [5]:
# creating a zero-dimensiosnal array
import numpy as np
arr = np.array(89)
print(arr)

89


In [6]:
# # creating a 1 dimensonal array
# Each value in a 1D array is )D array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [25]:
# Creating a 2D array
# IT has 1-D arrays as its elements.
arr = np.array([[12,3,45,7],[4,5,78,6]])
print(arr)

[[12  3 45  7]
 [ 4  5 78  6]]


In [32]:
# Creating a 3D array
arr = np.array([[[4,16,3,66],[4,17,72,6]],[[4,58,12,4],[5,16,67,4]]])
print(arr)

[[[ 4 16  3 66]
  [ 4 17 72  6]]

 [[ 4 58 12  4]
  [ 5 16 67  4]]]


In [54]:
# Creating a 4D array
arr = np.array([[[["string","python","56","57"],["45","67","Ture","False"],["45","89","float","complex"]]],[[["89","55","good","morning"],["45","56","rgfg","hjk"],["fgdfg","dfg","78","78"]]]])
arr

array([[[['string', 'python', '56', '57'],
         ['45', '67', 'Ture', 'False'],
         ['45', '89', 'float', 'complex']]],


       [[['89', '55', 'good', 'morning'],
         ['45', '56', 'rgfg', 'hjk'],
         ['fgdfg', 'dfg', '78', '78']]]], dtype='<U7')

In [39]:
arrv = np.array ([[[12,34],[23,45]],[[23,34],[34,54]]])
arrv

array([[[12, 34],
        [23, 45]],

       [[23, 34],
        [34, 54]]])

In [43]:
arr = np.array([[[[12,34],[32,11],[24,54]],[[34,56],[54,89],[56,45]]]])
arr

array([[[[12, 34],
         [32, 11],
         [24, 54]],

        [[34, 56],
         [54, 89],
         [56, 45]]]])

In [49]:
# What could be another way to crate an array
y = [1,2,3,4]
x= np.array(y)
x

array([1, 2, 3, 4])

In [50]:
x = np.array(range(10))
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
x.ndim

1

In [53]:
ar1 = np.array([[[1,2]]])  # Add as colams so given dimensonal array value
ar1.ndim

3

In [55]:
my_arr = np.arange(10000)
my_list = list(range(1000))


In [56]:
%timeit my_arr2 = my_arr * 2                    # our me a output

6.86 µs ± 20.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [59]:
%timeit my_list2 = [x*2 for x in my_list]

62.4 µs ± 601 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# <font size = 8> Data Types
- The bit is the most basic unit of information in computing
- The byte is a unit of information which contains 8 bits.

- <font size=4>Bit - 1
- <font size=4>Byte - 1 0 1 1 0 0 0 1

# <Font size =8> Data Type
- **Byte string** are constrained by the character encoding used. in character encoding like ASCII, each character is reprresented by a single byte, limiting the available character too the 128 ASCII character.
- **Unicode string** cover a much larger range of character, including those from various language amd special symbols.
- **"Object"** data type is used for all other data types.

# Three of Data types
- **Byte string**
   - bytes
   - bytes_
   - S
   - a

- **Unicode strings**
   - U
    - str
    - str_
    - unicode
    
- **object** 
    - object
    - O

In [6]:
import numpy as np


In [16]:
arr = np.array([2,"3",3.4,5j,True,False])
print(arr)
arr


['2' '3' '3.4' '5j' 'True' 'False']


array(['2', '3', '3.4', '5j', 'True', 'False'], dtype='<U64')

In [11]:
x = [4,6.7,"56",5j]
print(x)

[4, 6.7, '56', 5j]


In [25]:
import numpy as np
x = np.array([1,222222222222222222222222222222,3,-78],dtype="complex128")
x,x.dtype

(array([ 1.00000000e+00+0.j,  2.22222222e+29+0.j,  3.00000000e+00+0.j,
        -7.80000000e+01+0.j]),
 dtype('complex128'))

In [4]:
x = np.array([1,2,3,4],dtype="uint32")
x, x.dtype

(array([1, 2, 3, 4], dtype=uint32), dtype('uint32'))

In [8]:
x = np.array([2,3,0,1],dtype = "f2")
x, x.dtype

(array([2., 3., 0., 1.], dtype=float16), dtype('float16'))

In [10]:
x = np.array([3,5,6,7],dtype = "c8")
x, x.dtype

(array([3.+0.j, 5.+0.j, 6.+0.j, 7.+0.j], dtype=complex64), dtype('complex64'))

In [12]:
x = np.array([0,1,True,False,20],dtype = "bool")
x, x.dtype

(array([False,  True,  True, False,  True]), dtype('bool'))

In [27]:
x = np.array(["hello sir","hello maam","Good","python"],dtype = "S")  # Maxium length of a string in thiis ndarray is 10

x, x.dtype

(array([b'hello sir', b'hello maam', b'Good', b'python'], dtype='|S10'),
 dtype('S10'))

# <font size = 8> Numpy Array Inspection

In [2]:
import numpy as np

In [5]:
arr = np.array([["python ","world"],["hello"]])   # get the same value in array
print(arr.ndim)

1


C:\Users\gaura\AppData\Local\Temp\ipykernel_15536\1916127587.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([["python ","world"],["hello"]])   # get the same value in array


In [6]:
# ndarray.ndim - Returns the no of dimesnions
x = np.array([[1,2],[4,5]])
print(x.ndim)
x

2


array([[1, 2],
       [4, 5]])

In [31]:
# nd array.shape - Retruns the shape
x.shape

(2, 2)

In [49]:
x = np.array([[[6,3,4],[4,6,7],[5,8,6],[6,8,9]]])
print(x.ndim)
x

3


array([[[6, 3, 4],
        [4, 6, 7],
        [5, 8, 6],
        [6, 8, 9]]])

In [50]:
x.shape

(1, 4, 3)

In [51]:
x = np.array([[[[3,4,5,6],[5,6,7,6],[7,8,6,8],[5,7,9,6],[6,8,7,8]]]])
print(x.ndim)
x

4


array([[[[3, 4, 5, 6],
         [5, 6, 7, 6],
         [7, 8, 6, 8],
         [5, 7, 9, 6],
         [6, 8, 7, 8]]]])

In [52]:
x.shape

(1, 1, 5, 4)

In [41]:
x = np.array([[[3,6]],[[4,5]],[[3,4]],[[4,5]]])
print(x.ndim)
x

3


array([[[3, 6]],

       [[4, 5]],

       [[3, 4]],

       [[4, 5]]])

In [42]:
x.shape

(4, 1, 2)

In [49]:
import numpy as np

In [54]:
x = np.array([[[1,2],[4,5]],[[5,7],[5,7]]])
x.ndim
x

array([[[1, 2],
        [4, 5]],

       [[5, 7],
        [5, 7]]])

In [55]:
x.shape

(2, 2, 2)

In [2]:
import numpy as np

In [3]:

i = np.array([[[[3,4,5,6]]]])
print(i.ndim)
i

4


array([[[[3, 4, 5, 6]]]])

In [4]:
i.shape

(1, 1, 1, 4)

In [5]:
x = np.array([[[[1,2,4,5],[4,5,3,2]]],[[[2,4,6,7],[7,8,4,5]]],[[[4,5,5,5],[4,7,8,6]]]])
print(x.ndim)
x

4


array([[[[1, 2, 4, 5],
         [4, 5, 3, 2]]],


       [[[2, 4, 6, 7],
         [7, 8, 4, 5]]],


       [[[4, 5, 5, 5],
         [4, 7, 8, 6]]]])

In [6]:
x.shape

(3, 1, 2, 4)

In [7]:
(1,2,1,4)
(3,2,1,4)

(3, 2, 1, 4)

In [8]:
x= np.array([[[[3,4,5,6],[4,5,6,7],[4,16,3,66],[4,17,72,6]]],[[[4,58,12,4],[5,16,67,4],[5,6,7,8],[5,6,7,8]]],[[[4,58,12,4],[5,16,67,4],[5,6,7,8],[5,6,7,8]]]])
print(x.ndim)
x

4


array([[[[ 3,  4,  5,  6],
         [ 4,  5,  6,  7],
         [ 4, 16,  3, 66],
         [ 4, 17, 72,  6]]],


       [[[ 4, 58, 12,  4],
         [ 5, 16, 67,  4],
         [ 5,  6,  7,  8],
         [ 5,  6,  7,  8]]],


       [[[ 4, 58, 12,  4],
         [ 5, 16, 67,  4],
         [ 5,  6,  7,  8],
         [ 5,  6,  7,  8]]]])

In [9]:
x.shape

(3, 1, 4, 4)

In [10]:
x = np.array([[[10,2,3,6,7],[6,7,3,6,5],[4,6,5,4,3]],[[5,6,2,4,5],[8,6,5,6,6],[5,4,5,4,5]]])
x

array([[[10,  2,  3,  6,  7],
        [ 6,  7,  3,  6,  5],
        [ 4,  6,  5,  4,  3]],

       [[ 5,  6,  2,  4,  5],
        [ 8,  6,  5,  6,  6],
        [ 5,  4,  5,  4,  5]]])

In [11]:
x.shape

(2, 3, 5)

In [12]:
x = np.array([[[[2,3,4,5,4],[5,5,4,5,5],[4,5,3,4,8]],[[4,5,6,5,5],[5,6,7,6,6],[5,6,5,4,5]]]])
print(x.ndim)
x

4


array([[[[2, 3, 4, 5, 4],
         [5, 5, 4, 5, 5],
         [4, 5, 3, 4, 8]],

        [[4, 5, 6, 5, 5],
         [5, 6, 7, 6, 6],
         [5, 6, 5, 4, 5]]]])

In [13]:
x.shape

(1, 2, 3, 5)

In [41]:
x = np.array([[[[[2,3,4,5,4],[5,5,4,5,5],[3,4,5,3,4],[4,5,3,4,8]]],[[[4,5,6,5,5],[5,6,7,6,6],[4,5,6,3,3],[5,6,5,4,5]]]]])
print(x.ndim)
x

5


array([[[[[2, 3, 4, 5, 4],
          [5, 5, 4, 5, 5],
          [3, 4, 5, 3, 4],
          [4, 5, 3, 4, 8]]],


        [[[4, 5, 6, 5, 5],
          [5, 6, 7, 6, 6],
          [4, 5, 6, 3, 3],
          [5, 6, 5, 4, 5]]]]])

In [42]:
x.shape

(1, 2, 1, 4, 5)

In [35]:
# Change the shape of an array
# Shape of an array also gives its size and no of dimensions
# for size, multiply the values in the shape tuple e.g (2,3) --- 2*3 = 6
# for dimesnsions, count the no of value in  the shape of tuple e.g (2,3) -- 2 Dimesnional 
# While changing the shape of an array keep in mind that its size will not change .
import numpy as np
x = np.array([1,2,3,4])
print(x.shape)
print(x)
# (2,2) - - 2*2 = 4
# (2,3) - - 2*3 = 6
x.shape = (1,2,1,2) # 1*2*1*2 = 4
print(x)

(4,)
[1 2 3 4]
[[[[1 2]]

  [[3 4]]]]


In [34]:
x = np.array ([2,4,3,2,1,5,4,6])
print(x.shape)
print(x)
x.shape = (8)
print(x)

(8,)
[2 4 3 2 1 5 4 6]
[2 4 3 2 1 5 4 6]


In [29]:
x = np.array ([2,4,3,2,1,5,4,6])
print(x.shape)
print(x)
x.shape = (1,8)
print(x)

(8,)
[2 4 3 2 1 5 4 6]
[[2 4 3 2 1 5 4 6]]


In [28]:
x = np.array ([2,4,3,2,1,5,4,6])
print(x.shape)
print(x)
x.shape = (2,2,2)
print(x)

(8,)
[2 4 3 2 1 5 4 6]
[[[2 4]
  [3 2]]

 [[1 5]
  [4 6]]]


In [30]:
x = np.array ([2,4,3,2,1,5,4,6])
print(x.shape)
print(x)
x.shape = (2,2,1,2)
print(x)

(8,)
[2 4 3 2 1 5 4 6]
[[[[2 4]]

  [[3 2]]]


 [[[1 5]]

  [[4 6]]]]


In [32]:
x = np.array ([2,4,3,2,1,5,4,6])
print(x.shape)
print(x)
x.shape = (1,2,1,1,4)
print(x)

(8,)
[2 4 3 2 1 5 4 6]
[[[[[2 4 3 2]]]


  [[[1 5 4 6]]]]]


In [33]:
x = np.array ([2,4,3,2,1,5,4,6])
print(x.shape)
print(x)
x.shape = (2,2,1,1,1,2)
print(x)

(8,)
[2 4 3 2 1 5 4 6]
[[[[[[2 4]]]]



  [[[[3 2]]]]]




 [[[[[1 5]]]]



  [[[[4 6]]]]]]


In [2]:
import numpy as np

In [5]:
# ndarray.size  - Return thr no of elements
x = np.array([1,2,3,4,5])
x.size

5

In [6]:
# ndarray.dtype - Retrun the data type of the elements in the ndarray
x.dtype

dtype('int32')

# <font size = 6> Methods and Functions used with ndarrays

In [2]:
import numpy as np


<font size = 6> np.ones

In [49]:
#np.ones(shape,dtype)  - Return a new array of given shape and type , filled with ones
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [8]:
np.ones((2,3,4)).dtype

dtype('float64')

In [10]:
x = np.ones((2,3,4)).dtype   # es type ka object hai
type(x)

numpy.dtype[float64]

In [65]:
np.ones((1,5),"int32")

array([[1, 1, 1, 1, 1]])

# np.zeros

In [23]:
# np.zeros (shape,dtype) - Retrun a new array of given shape and type , filled with zeros
np.zeros((1,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
np.zeros((2,5),"B")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

# np.empty

In [11]:
# np.empty (shape,dtype) -
# Return a new array of given shape and type, without initializing entries.
np.empty((2,1),"uint")

array([[1065353216],
       [1065353216]], dtype=uint32)

# np.full

In [12]:
# np.full (shape,fill_value,dtype) -
# Return a new array of given shape and type, filled with fill_value

np.full((2,2,4),80)

array([[[80, 80, 80, 80],
        [80, 80, 80, 80]],

       [[80, 80, 80, 80],
        [80, 80, 80, 80]]])

In [31]:
np.full((2,2,4),[2,3])


ValueError: could not broadcast input array from shape (2,) into shape (2,2,4)

# np .arange

In [3]:
#np.arange (start,step,dtype) - Return evenly spaced values within a given interval.
np.arange(3,10,2)

array([3, 5, 7, 9])

In [14]:
np.arange(3.3,10.2,2.3)

array([3.3, 5.6, 7.9])

In [32]:
np.arange(4.4,12.2,2.2)

array([ 4.4,  6.6,  8.8, 11. ])

 <font size = 5>np.linspace

In [27]:
# numpy.linspace (start, stop ,num=50, endpoint=True,dtype)
# Return evenly spaced number over a specified interval.
# What do num = 50 and endpoint = True sugget here?
# num =50 in the default value of num when not given ,i.e , it will give 50 numbers in the range 
# endpoint = True is the default value of endpoint which tells us that the stop value in inclusive by default
np.linspace(2,10,num=2,endpoint=False)

array([2., 6.])

In [16]:
np.linspace(2,10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [38]:
x = np.array(np.array({2,3,4}))
x

array({2, 3, 4}, dtype=object)

In [39]:
np.array(x)

array({2, 3, 4}, dtype=object)

In [51]:
x = np.array([2,3,4,np.linspace(2,3,5)],dtype= "O")
x

array([2, 3, 4, array([2.  , 2.25, 2.5 , 2.75, 3.  ])], dtype=object)

In [43]:
x = np.array([np.arange(2,10,2)])
x

array([[2, 4, 6, 8]])

In [ ]:
# Shape Manipulaton in Numpy

In [2]:
import numpy as np

In [18]:
# reshape()
x = np.array([1,2,3,4])
print(x.shape)
x = x.reshape(2,2)
print(x)

(4,)
[[1 2]
 [3 4]]


In [19]:
x

array([[1, 2],
       [3, 4]])

In [20]:
x.reshape(1,1,2,2,1)

array([[[[[1],
          [2]],

         [[3],
          [4]]]]])

In [21]:
x

array([[1, 2],
       [3, 4]])

In [16]:
# .flatten()   ----- flattens the arrays in one
y = x.flatten()
y [0]=23
y

array([23,  2,  3,  4])

In [17]:
# .ravel()
x.ravel()
x[0]=23
x

array([[23, 23],
       [ 3,  4]])

In [10]:
x

array([[1, 2],
       [3, 4]])

In [11]:
# .resize () -- The difference b\w resize and reshape is that resize change
# the value of array where as reshape make the copy of the array
x.resize(4,1)


In [12]:
x

array([[1],
       [2],
       [3],
       [4]])

In [14]:
x.reshape(2,2)


array([[1, 2],
       [3, 4]])

# Stacking 
- Join a sequence of arrays along a new axis.

In [17]:
# stack 
#2d
import numpy as np
n1 = np.array([[1,2,3],
             [5,6,7]])
n2 = np.array([[4,8,9],
              [11,12,10]])
print(f" n1
      
      : \n {n1} \nn2:  \n {n2} \n")
print("for axis=0:\n ",np.stack((n1,n2),axis=0),"\n") #row-wise stacking

 n1 : 
 [[1 2 3]
 [5 6 7]] 
n2:  
 [[ 4  8  9]
 [11 12 10]] 

for axis=0:
  [[[ 1  2  3]
  [ 5  6  7]]

 [[ 4  8  9]
  [11 12 10]]] 



In [19]:
print(f" n1 : \n {n1} \nn2:  \n {n2} \n")
print("for axis=1:\n ",np.stack((n1,n2),axis=1),"\n")

 n1 : 
 [[1 2 3]
 [5 6 7]] 
n2:  
 [[ 4  8  9]
 [11 12 10]] 

for axis=1:
  [[[ 1  2  3]
  [ 4  8  9]]

 [[ 5  6  7]
  [11 12 10]]] 



In [22]:
print(f" n1 : \n {n1} \nn2:  \n {n2} \n")
print("for axis=1:\n ",np.stack((n1,n2),axis=1),"\n","for axis=0: \n",np.stack((n1,n2),axis=0),"\n")

 n1 : 
 [[1 2 3]
 [5 6 7]] 
n2:  
 [[ 4  8  9]
 [11 12 10]] 

for axis=1:
  [[[ 1  2  3]
  [ 4  8  9]]

 [[ 5  6  7]
  [11 12 10]]] 
 for axis=0: 
 [[[ 1  2  3]
  [ 5  6  7]]

 [[ 4  8  9]
  [11 12 10]]] 



In [23]:
print(f" n1 : \n {n1} \nn2:  \n {n2} \n")
print("for axis=1:\n ",np.stack((n1,n2),axis=1),"\n","for axis=2: \n",np.stack((n1,n2),axis=2),"\n")

 n1 : 
 [[1 2 3]
 [5 6 7]] 
n2:  
 [[ 4  8  9]
 [11 12 10]] 

for axis=1:
  [[[ 1  2  3]
  [ 4  8  9]]

 [[ 5  6  7]
  [11 12 10]]] 
 for axis=2: 
 [[[ 1  4]
  [ 2  8]
  [ 3  9]]

 [[ 5 11]
  [ 6 12]
  [ 7 10]]] 



In [24]:
print(f" n1 : \n {n1} \nn2:  \n {n2} \n")
print("for axis=1:\n ",np.stack((n1,n2),axis=1),"\n","for axis=3: \n",np.stack((n1,n2),axis=3),"\n")

 n1 : 
 [[1 2 3]
 [5 6 7]] 
n2:  
 [[ 4  8  9]
 [11 12 10]] 



AxisError: axis 3 is out of bounds for array of dimension 3

In [26]:
n1 = np.array([1,2,3])
n2 = np.array([4,8,9])
print(f" n1 : \n {n1} \nn2:  \n {n2} \n")
print("for axis=0:\n ",np.stack((n1,n2),axis=0),"\n""\n","for axis=1: \n",np.stack((n1,n2),axis=1),"\n")

 n1 : 
 [1 2 3] 
n2:  
 [4 8 9] 

for axis=0:
  [[1 2 3]
 [4 8 9]] 

 for axis=1: 
 [[1 4]
 [2 8]
 [3 9]] 



# Concatenation 
- Join a sequence of arrays along an existing axis.


In [1]:
import numpy as np

In [4]:
x = np.array([[1,2,3],
            [4,5,6]])
y = np.array([[7,8,9],
             [10,11,12]])

print(f"x : \n {x} \ny: \n {y} \n")
print("Resulting array : \n",np.concatenate((x,y),axis =0))  # row - wise concatenation

x : 
 [[1 2 3]
 [4 5 6]] 
y: 
 [[ 7  8  9]
 [10 11 12]] 

Resulting array : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
print(f" x : \n {x} \n y : \n {y} \n")
print("Resulting array : \n",np.concatenate((x,y),axis =1))

 x : 
 [[1 2 3]
 [4 5 6]] 
 y : 
 [[ 7  8  9]
 [10 11 12]] 

Resulting array : 
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [12]:
#1d 
n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])
print(f"n1 :  {n1} \nn2: \n {n2} \n")
print("For axis=0:\n",np.concatenate((n1,n2),axis=0),"\n")

n1 :  [1 2 3 4] 
n2: 
 [5 6 7 8] 

For axis=0:
 [1 2 3 4 5 6 7 8] 



In [11]:
print(f"n1 :  {n1} \nn2: \n {n2} \n")
print("For axis=0:\n0",np.concatenate((n1,n2),axis=1),"\n")

n1 :  [1 2 3 4] 
n2: 
 [5 6 7 8] 



AxisError: axis 1 is out of bounds for array of dimension 1

# hstack and vstack

In [14]:
# 2D array 
x = np.array([[1,2,3],
              [4,5,6]])
y = np.array([[7,8,9],
             [10,11,12]])
np.hstack((x,y))    #np.concatenate((x,y),axis =1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [15]:
np.vstack((x,y))   #np.concatenate((x,y),axis =0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
#1d
n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])

np.hstack((n1,n2))      # np.concatenate((n1,n2),axis = 0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
np.vstack((n1,n2))     # np.stack((n1,n2),axis = 0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Indexing ,Slicing & Striding


In [2]:
import numpy as np

In [3]:
# 1d
# (Axis 0,)
# (Columns,)
# (0D,)
x = np.array([1,2,3,4])
print(x[2])
print(x[3])

3
4


In [4]:
# 2d 
# (Axis 0 , Axis 1)
# (Rows , Columns)
# (1D,0D)
x = np.array([[1,2,3,4],
            [5,6,7,8]])
x [ 0,1]   # Perferred way

2

In [5]:
x[1][3]  # Alternative way

8

In [6]:
x = np.array([1,2,3,4])
x[-2]

3

In [7]:
x = np.array([[1,2,3,4],
             [5,6,7,8]])
x[-1]

array([5, 6, 7, 8])

In [8]:
# indexing in 3d array
# (AXis 0,Axis1 , Axis 2)
# (2d,1d,0d)
import numpy as np

x = np.array ([[[1,2,3,4],
                [5,6,7,8]],
               [[9,10,11,12],
                [13,14,15,16]]])
print(x[1])
print(x[0])

[[ 9 10 11 12]
 [13 14 15 16]]
[[1 2 3 4]
 [5 6 7 8]]


In [22]:
x[1,0,3]

12

In [3]:
x[0,0]

array([1, 2, 3, 4])

In [4]:
x[0,1,3]

8

In [34]:
x[1,0,3]

12

# Slicing & Strinding
start(inclusive): stop (exclusive): step

In [36]:
#1d 
x = np.array([1,2,3,4])
x[0:4:2]

array([1, 3])

In [37]:
x[::2]

array([1, 3])

In [8]:
#slicing in 2d
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [16]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a[0:2,0]


array([1, 4])

In [5]:
a[0,1:3]

array([2, 3])

# Arithmetic with NumPy
- Any operation between equal-size arrays happens element-wise.

In [6]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[2,3,4],
               [5,6,7]])

a+b

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [7]:
a*b

array([[ 2,  6, 12],
       [20, 30, 42]])

In [18]:
a-b

array([[-1, -1, -1],
       [-1, -1, -1]])

In [9]:
a/b

array([[0.5       , 0.66666667, 0.75      ],
       [0.8       , 0.83333333, 0.85714286]])

In [10]:
a//b

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
a**b

array([[     1,      8,     81],
       [  1024,  15625, 279936]])

In [21]:
a%b

array([[1, 2, 3],
       [4, 5, 6]])

# Arithmetic operations with scalars propagate the scalar argument to each element in the array
- Operations between differently sized arrays is called broadcasting 

In [22]:
a*2 # Broadcasting 

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [23]:
a-2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [26]:
a-np.array([2])

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [30]:
a+2+3+4


array([[10, 11, 12],
       [13, 14, 15]])

# Universal Functions 
- A universal function, or ufunc, is a function that perfrom element-wise operations on data in ndarrays.

In [31]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.add(a,b)  # or a+b

array([ 6,  8, 10, 12])

In [32]:
np.subtract(b,a)  # or b-a

array([4, 4, 4, 4])

In [33]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [35]:
import numpy

In [36]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__packag

# Pseudo-Random Number Generation

In [24]:
# In python we have a built-in module random
import random
random.random()

0.20933443731398393

In [29]:
random.seed(2)              # same seed value will generate the same random no.
random.random()

0.9560342718892494

In [1]:
import numpy as np
np.random.seed(1)
np.random.random()


0.417022004702574

# Boolean Array

In [2]:
import numpy as np
names = np.array(["Gaurav","Rohit","Rishi","Himanshu","Gaurav"])


In [3]:
names == "Gaurav"  # this gives a boolean array

array([ True, False, False, False,  True])

In [4]:
names[names=="Gaurav"]

array(['Gaurav', 'Gaurav'], dtype='<U8')

In [6]:
names[names=="Gaurav"][0]

'Gaurav'

In [7]:
names[names=="Gaurav"][4]   # there is not a indexing value link than get of out of box

IndexError: index 4 is out of bounds for axis 0 with size 2

In [2]:
import numpy as np


# Swap two columns in a 2d numpy array.


In [3]:
array = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
array[:,[0,1]] = array [:,[1,0]]
print(array)

[[2 1 3]
 [5 4 6]
 [8 7 9]]


# Swap two rows in a 2d array.

In [5]:
array = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
array[[0,1]]=array[[1,0]]
array

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

# Reverse all the rows of 2d array

In [8]:
array = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
array[:,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

# Extract all numbers between a given range from aone dimensionalndarray

In [9]:
# method 1
y = np.array([1,3,5,4,6,3,6,4,3,2,10])
y = np.array([i for i in y if 4<=i<=10])
y

array([ 5,  4,  6,  6,  4, 10])

In [10]:
# method 2 
y = np.array([1,3,5,4,6,3,6,4,3,2,10])
y[(y>=4)&(y<=10)]

array([ 5,  4,  6,  6,  4, 10])

In [11]:
(y>=4)

array([False, False,  True,  True,  True, False,  True,  True, False,
       False,  True])

In [ ]:
y[(y>=4)&(y<=10)]

In [23]:
x = np.array([[[[1,2]],
              [[3,4]]],
            [[[5,6]],
           [[7,8]]]])
x.shape

(2, 2, 1, 2)